baseURL = "https://il0g.com"
languageCode = "en-us"
title = "il0g.com"
theme = "hugo-theme-console"
sectionPagesMenu = "main"


[params]
  # Cutting off the page title to two chars for mobile (console-demo -> co)
  titleCutting = false

  # Set the animation style -- https://animate.style/
  # To disable animations, please remove or comment animationStyle parameter
  #animateStyle = "animated fadeIn fast"

  # Reference any custom CSS I make in the static/ dir
  #custom_css = ["till_custom_style.css"]

  [[params.navlinks]]
  name = "posts"
  url = "posts/"

  [[params.navlinks]]
  name = "photos"
  url = "photos/"

  [[params.navlinks]]
  name = "about"
  url = "about/"

  [[params.navlinks]]
  name = "contact"
  url = "contact/"
