name = "il0g.com"
license = "MIT"
licenselink = "https://github.com/mrmierzejewski/hugo-theme-console/blob/master/LICENSE"
description = "A minimal, responsive and light theme for Hugo inspired by Linux console."
homepage = "https://github.com/varunpilankar/il0g.com"
tags = ["blog", "gallery", "portfolio", "console", "terminal", "clean", "personal", "minimal", "monotone", "simple", "technical", "responsive", "mobile", "minimalist", "retro", "animation"]
features = ["disqus", "responsive", "google analytics"]
min_version = "0.81.0"

[author]
    name = "Indrasen Pilankar"
    homepage = "https://il0g.com"
    github = "https://github.com/varunpilankar"

[original]
    author = "Jonas D."
    homepage = "https://terminalcss.xyz/"
    repo = "https://github.com/Gioni06/terminal.css"